#!/bin/bash

# GitHub Codespaces / Online Development Guide for PSP Homebrew
# Since local macOS Monterey has compatibility issues, use cloud development

echo "================================================"
echo "PSP Development via GitHub Codespaces"
echo "================================================"
echo ""
echo "Due to macOS Monterey limitations, the recommended"
echo "approach is to use GitHub Codespaces (free!)."
echo ""
echo "SETUP STEPS:"
echo "============"
echo ""
echo "1. Push your code to GitHub:"
echo "   cd /Users/harriahola/Projects/PSP/helloworld"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial PSP Hello World'"
echo "   # Create repo on github.com and push"
echo ""
echo "2. Open GitHub Codespaces:"
echo "   - Go to your repository on github.com"
echo "   - Click 'Code' → 'Codespaces' → 'Create codespace'"
echo "   - Wait for environment to load (Ubuntu Linux)"
echo ""
echo "3. In the Codespace terminal, run:"
echo "   sudo apt-get update"
echo "   sudo apt-get install -y build-essential cmake git"
echo "   export PSPDEV=\"\$HOME/pspdev\""
echo "   export PATH=\"\$PATH:\$PSPDEV/bin\""
echo "   git clone https://github.com/pspdev/psptoolchain.git"
echo "   cd psptoolchain"
echo "   ./toolchain.sh"
echo ""
echo "4. Build your Hello World:"
echo "   cd /workspaces/your-repo"
echo "   make"
echo ""
echo "5. Download EBOOT.PBP to your Mac"
echo ""
echo "================================================"
echo ""
echo "GitHub gives you 60 hours/month free!"
echo "Perfect for PSP development."
echo ""
